/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenImport } from './routes/authen'
import { Route as UserImport } from './routes/_user'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as RedirectIdImport } from './routes/_redirect.$id'
import { Route as AuthSettingsImport } from './routes/_auth/settings'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthLinkIdImport } from './routes/_auth/link.$id'
import { Route as legacyLocaleLocaleImport } from './routes/(legacy)/_locale.$locale'

// Create/Update Routes

const AuthenRoute = AuthenImport.update({
  id: '/authen',
  path: '/authen',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RedirectIdRoute = RedirectIdImport.update({
  id: '/_redirect/$id',
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLinkIdRoute = AuthLinkIdImport.update({
  id: '/link/$id',
  path: '/link/$id',
  getParentRoute: () => AuthRoute,
} as any)

const legacyLocaleLocaleRoute = legacyLocaleLocaleImport.update({
  id: '/(legacy)/_locale/$locale',
  path: '/$locale',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/authen': {
      id: '/authen'
      path: '/authen'
      fullPath: '/authen'
      preLoaderRoute: typeof AuthenImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/_redirect/$id': {
      id: '/_redirect/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof RedirectIdImport
      parentRoute: typeof rootRoute
    }
    '/(legacy)/_locale/$locale': {
      id: '/(legacy)/_locale/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof legacyLocaleLocaleImport
      parentRoute: typeof rootRoute
    }
    '/_auth/link/$id': {
      id: '/_auth/link/$id'
      path: '/link/$id'
      fullPath: '/link/$id'
      preLoaderRoute: typeof AuthLinkIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthLinkIdRoute: typeof AuthLinkIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthLinkIdRoute: AuthLinkIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof UserRoute
  '/authen': typeof AuthenRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/$id': typeof RedirectIdRoute
  '/$locale': typeof legacyLocaleLocaleRoute
  '/link/$id': typeof AuthLinkIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof UserRoute
  '/authen': typeof AuthenRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/$id': typeof RedirectIdRoute
  '/$locale': typeof legacyLocaleLocaleRoute
  '/link/$id': typeof AuthLinkIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_user': typeof UserRoute
  '/authen': typeof AuthenRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_redirect/$id': typeof RedirectIdRoute
  '/(legacy)/_locale/$locale': typeof legacyLocaleLocaleRoute
  '/_auth/link/$id': typeof AuthLinkIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/authen'
    | '/dashboard'
    | '/settings'
    | '/$id'
    | '/$locale'
    | '/link/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/authen'
    | '/dashboard'
    | '/settings'
    | '/$id'
    | '/$locale'
    | '/link/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_user'
    | '/authen'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_redirect/$id'
    | '/(legacy)/_locale/$locale'
    | '/_auth/link/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRoute
  AuthenRoute: typeof AuthenRoute
  RedirectIdRoute: typeof RedirectIdRoute
  legacyLocaleLocaleRoute: typeof legacyLocaleLocaleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRoute,
  AuthenRoute: AuthenRoute,
  RedirectIdRoute: RedirectIdRoute,
  legacyLocaleLocaleRoute: legacyLocaleLocaleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_user",
        "/authen",
        "/_redirect/$id",
        "/(legacy)/_locale/$locale"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/settings",
        "/_auth/link/$id"
      ]
    },
    "/_user": {
      "filePath": "_user.tsx"
    },
    "/authen": {
      "filePath": "authen.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_redirect/$id": {
      "filePath": "_redirect.$id.tsx"
    },
    "/(legacy)/_locale/$locale": {
      "filePath": "(legacy)/_locale.$locale.tsx"
    },
    "/_auth/link/$id": {
      "filePath": "_auth/link.$id.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
